console.log("Jai Sai Master");
console.log("Jai Bapuji Maharaj");

//  String Search Methods()
/* 
1. indexOf()
2. lastIndexOf()
3. search()
4. match()
5. matchAll()
6. Includes()
7. startsWith()
8. endsWith()   */

//  indexOf()
/*let a = "Bhanu prakash";

let index = a.indexOf("a");
console.log(index);

index = a.indexOf("a", 6);
console.log(index); */

// lastIndexOf()

/*a = "Bhanu prakash";
let last = a.lastIndexOf("a", 5);

console.log(last); */

// search()

/*let a = "Bhanu prakash";

console.log(a.search("ha")); */

// match()

/*let a = "Bhanu prakash";
console.log(a.match("ha")); */

// matchAll()

/* a = "Bhanu prakash";
console.log(Array.from(a.matchAll("a"))); */

// includes()

/* a = "Bhanu prakash";
console.log(a.includes("u"));*/

// StartsWith()
/*let a = "Bhanu prakash";
console.log(a.startsWith("a", 2)); */

// endsWith()

/*let a = "Bhanu prakash";
console.log(a.endsWith("a", 3)); */

// given introduction to  array's
